version: '1'

services:
  master:
    image: locust:v1
    ports:
     - "8089:8089"
    volumes:
      - ./:/home/dongmanlocustproject
    command: -f /home/dongmanlocustproject/locustfile.py --master

  worker:
    image: locust:v1
    volumes:
      - ./:/home/dongmanlocustproject
    command: -f /home/dongmanlocustproject/locustfile.py --worker --master-host master